---
title: "Bayesian Regression: Theory & Practice"
author: "Michael Franke"
---

This site provides material for an intermediate level course on Bayesian linear regression modeling.
The course presupposes some prior exposure to statistics and some acquaintance with R.

## Intended audience

This course is designed for people who have completed a first, introductory course on data analysis, which has conveyed roughly the following: 

- basic knowledge of R and, ideally, the tidyverse
- basic familiarity with Bayesian reasoning (prior, likelihood, posterior)
- some prior exposure to regression modeling (Bayesian or otherwise)

## Scope

The aim of this course is to increase students' overview over topics relevant for intermediate to advanced Bayesian regression modeling. 
The course focuses on Bayesian multi-level generalized linear models as implemented in the `brms` package.
It covers, among other things, the following theoretical and practical aspects:

- prior and posterior model checking
- MCMC methods (HMC diagnostics)
- generalized linear models (ordered logit, multinomial, Poisson, Beta ...)
- distributional and non-linear models (GAMs, Gaussian processes)
- model comparison (Bayes factors, cross-validation)

## Additional material

This course contains a short [tutorial on Bayesian modeling](practice-sheets/00a-examples-WebPPL.html), and a brief [tutorial on wrangling and plotting in the tidyverse](practice-sheets/00b-wrangling-plotting.html).

For more background, a companion to this course, is the introductory webbook["An introduction to Data Analysis"](https://michael-franke.github.io/intro-data-analysis/index.html), which  covers R, tidyverse, Bayesian and, eventually, also frequentist statistics.
This course presupposes roughly the content covered in Chapters 2--9 and 12--13.

There is also a [cheat sheet on BRMS](practice-sheets/09a-cheat-sheet.html) for reference.

## Acknowledgements

Part of the hands-on material (wrangling, plotting, simple regression modeling) was used in a previous course, co-taught with Timo Roettger.
My gratitude for his permission to build on it here.
The tutorial on contrast coding was first authored by Polina Tsvilodub.
The initial exercises for building Bayesian intuitions using WebPPL were inspired by and elaborate on material first created by Michael Henry Tessler in [this webbook](https://mhtess.github.io/bdappl/).
